[theme]
name = "plain"
[theme.overrides]
separator = "  "
idle_fg = "#999999"
info_fg = "#999999"
good_fg = "#999999"
critical_fg = "#FFFFFF"
critical_bg = "#D70000"
warning_fg = "#D75F00"

[icons]
name = "none"
[icons.overrides]
net_down = ""
volume_muted = "MUTE"

[[block]]
block = "custom"
command = ''' doas xbps-install -nSu | wc -l '''
interval = 300
on_click = "foot xi -Su"

#[[block]]
#block = "bluetooth"
#mac = "DB:3C:B8:46:FA:4F"
#
#[[block]]
#block = "backlight"
#
#[[block]]
#block = "sound"

[[block]]
block = "cpu"
interval = 1
format = "{utilization}% {frequency}GHz"
on_click = "foot htop"

[[block]]
block = "net"
device = "wlp0s20f3"
format = "{ssid} ({signal_strength} {speed_down})"
interval = 5
use_bits = false
hide_missing = true

[[block]]
block = "net"
device = "enp42s0"
format = "{ip}{speed_down}"
interval = 5
use_bits = false
hide_missing = true

[[block]]
block = "battery"
interval = 10
format = "{percentage}% ({time})"
allow_missing = true
hide_missing = true

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
