[theme]
name = "plain"

[theme.overrides]
idle_bg = "#323232"
warning_bg = "#323232"
critical_bg = "#323232"
good_bg = "#323232"
info_bg = "#323232"
idle_fg = "#999999"
info_fg = "#999999"
good_fg = "#999999"
separator_bg = "#323232"
separator_fg = "#777777"
separator = "|"

# [[block]]
# block = "cpu"
# interval = 10
# format = "{utilization}% {frequency}"

[[block]]
block = "load"
interval = 10
format = "{1m}"

# [[block]]
# block = "net"
# device = "wlo1"
# # interval = 5
# # use_bits = false

[[block]]
block = "custom"
command = "/home/kkga/.config/dwm-bar/bar-functions/dwm_resources.sh"
interval = 5

[[block]]
block = "networkmanager"
device_format = "{typename} {ap} {ips}"

# [[block]]
# block = "uptime"

[[block]]
block = "sound"

[[block]]
block = "keyboard_layout"
driver = "sway"
format = "KB {layout}"
sway_kb_identifier = "65261:24672:ZSA_Planck_EZ_Keyboard"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
