[theme]
name = "plain"

[theme.overrides]
idle_bg = "#000000"
warning_bg = "#000000"
critical_bg = "#000000"
good_bg = "#000000"
info_bg = "#000000"
idle_fg = "#999999"
info_fg = "#999999"
good_fg = "#999999"
separator_bg = "#000000"
separator_fg = "#777777"
separator = "┊"

[[block]]
block = "focused_window"
max_width = 50
show_marks = "all"

[[block]]
block = "cpu"
interval = 10
format = "{utilization}% {frequency}"

[[block]]
block = "custom"
command = "/home/kkga/.config/dwm-bar/bar-functions/dwm_resources.sh"
interval = 5

[[block]]
block = "custom"
command = "xbps-install -Sun | wc -l | xargs -I % sh -c 'echo XBPS %'"
interval = 600

[[block]]
block = "sound"

# [[block]]
# block = "custom"
# command = ''' cat /sys/class/thermal/thermal_zone0/temp | awk '{printf("%.1f\n",$1/1000)}' '''

[[block]]
block = "networkmanager"
ap_format = "WIFI {ssid} ({strength}%)"
device_format = "{ap}"

[[block]]
block = "uptime"

# [[block]]
# block = "keyboard_layout"
# driver = "sway"
# format = "KB {layout}"
# sway_kb_identifier = "65261:24672:ZSA_Planck_EZ_Keyboard"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
