[menu]
executable = 'fzf-menu'
args = ['--bind=tab:down,btab:up']

[format]
window_format = '[{workspace_name}] {app_name}: {urgency_start}{title}{urgency_end} — '
workspace_format = '-{name}-'
urgency_start = '!!! '
urgency_end = ' !!!'
