tap "apenngrace/vulkan"
tap "beeftornado/rmtree"
tap "bvaisvil/zenith"
tap "caryll/tap"
tap "clementtsang/bottom"
tap "d12frosted/emacs-plus"
tap "denisidoro/tools"
tap "dustinwilson/tap"
tap "extrawurst/tap"
tap "federico-terzi/espanso"
tap "github/gh"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "jesseduffield/lazygit"
tap "jmacdonald/amp"
tap "kkga/godot-nightly"
tap "koekeishiya/formulae"
tap "lukakerr/things"
tap "mananapr/cfiles"
tap "martido/graph"
tap "mas-cli/tap"
tap "mongodb/brew"
tap "neovim/neovim"
tap "somdoron/formulae"
tap "universal-ctags/universal-ctags"
tap "vitorgalvao/tiny-scripts"
brew "gdbm"
brew "sqlite"
brew "python@3.8"
brew "asciinema"
brew "awscli"
brew "bat"
brew "icu4c"
brew "bitwarden-cli"
brew "fontconfig"
brew "catimg"
brew "coreutils"
brew "libevent"
brew "crystal"
brew "dante"
brew "deno"
brew "dust"
brew "exa"
brew "fd"
brew "flac"
brew "python"
brew "libvorbis"
brew "sdl2"
brew "ffmpeg"
brew "fish"
brew "fzf"
brew "geoip"
brew "git"
brew "git-delta"
brew "git-extras"
brew "git-lfs"
brew "gnu-getopt"
brew "git-now"
brew "go"
brew "htop"
brew "hub"
brew "hyperfine"
brew "ifstat"
brew "libtool"
brew "imagemagick"
brew "irssi"
brew "jq"
brew "lf"
brew "libuv"
brew "links"
brew "mad"
brew "mas"
brew "mdcat"
brew "molten-vk", link: false
brew "mpc"
brew "msmtp"
brew "neofetch"
brew "neovim", args: ["HEAD"]
brew "nnn"
brew "nushell"
brew "openvpn"
brew "pandoc"
brew "prettier"
brew "redis"
brew "rename"
brew "restic"
brew "ripgrep"
brew "ripmime"
brew "scdoc"
brew "scons"
brew "sk"
brew "speedtest-cli"
brew "starship"
brew "terminal-notifier"
brew "tig"
brew "tldr"
brew "tmux"
brew "todo-txt"
brew "tokei"
brew "trash"
brew "vcprompt"
brew "vulkan-headers", link: false
brew "w3m"
brew "weechat"
brew "wget"
brew "wimlib"
brew "yadm"
brew "yarn"
brew "yasm"
brew "youtube-dl"
brew "yq"
brew "zola"
brew "bvaisvil/zenith/zenith"
brew "extrawurst/tap/gitui"
brew "federico-terzi/espanso/espanso"
brew "github/gh/gh"
brew "jesseduffield/lazygit/lazygit"
brew "koekeishiya/formulae/skhd"
brew "koekeishiya/formulae/yabai"
brew "mongodb/brew/mongodb-community@3.6", link: true
brew "somdoron/formulae/spacebar"
brew "universal-ctags/universal-ctags/universal-ctags", args: ["HEAD"]
brew "vitorgalvao/tiny-scripts/cask-repair"
cask "alfred"
cask "appcleaner"
cask "balenaetcher"
cask "bitwarden"
cask "blender"
cask "cakebrew"
cask "chromium"
cask "coconutbattery"
cask "deckset"
cask "dejalu"
cask "docker"
cask "dozer"
cask "drawio"
cask "dropshare"
cask "etrecheckpro"
cask "figma"
cask "firefox"
cask "firefox-developer-edition"
cask "firefox-nightly"
cask "font-anka-coder"
cask "font-cascadia"
cask "font-cozette"
cask "font-envy-code-r"
cask "font-fantasque-sans-mono"
cask "font-go-mono"
cask "font-hack"
cask "font-inter"
cask "font-iosevka-aile"
cask "font-iosevka-ss10"
cask "font-jetbrains-mono"
cask "font-m-plus"
cask "font-mononoki"
cask "font-spleen"
cask "font-sudo"
cask "font-terminus"
cask "fontforge"
cask "gifox"
cask "github"
cask "gltfquicklook"
cask "godot"
cask "godot-nightly"
cask "handbrake"
cask "iina"
cask "intel-power-gadget"
cask "iterm2"
cask "itsycal"
cask "kap"
cask "karabiner-elements"
cask "keycastr"
cask "kitty"
cask "kode54-cog"
cask "latest"
cask "little-snitch"
cask "lulu"
cask "maccy"
cask "magicavoxel"
cask "menumeters"
cask "michaelvillar-timer"
cask "min"
cask "nativedisplaybrightness"
cask "netnewswire"
cask "notable"
cask "numi"
cask "obs"
cask "podman"
cask "protonvpn"
cask "quakespasm"
cask "quitter"
cask "qutebrowser"
cask "scapple"
cask "screens-connect"
cask "sf-symbols"
cask "shifty"
cask "sketch"
cask "slack"
cask "sloth"
cask "steam"
cask "sublime-merge"
cask "sublime-text"
cask "syncthing"
cask "table-tool"
cask "taskexplorer"
cask "taskpaper"
cask "telegram"
cask "textmate"
cask "tomighty"
cask "transmission"
cask "twine"
cask "ubersicht"
cask "unetbootin"
cask "viscosity"
cask "visual-studio-code"
cask "vorta"
cask "vscodium"
cask "vulkan-sdk"
cask "zoomus"
mas "1Blocker", id: 1107421413
mas "Annotate", id: 918207447
mas "app.seashore", id: 1448648921
mas "Blackmagic RAW Speed Test", id: 1466185689
mas "Bumpr", id: 1166066070
mas "Claquette", id: 587748131
mas "Disk Speed Test", id: 425264550
mas "GIF Brewery 3", id: 1081413713
mas "Gifski", id: 1351639930
mas "Gladys", id: 1382386877
mas "GoodNotes", id: 1480793815
mas "iA Writer", id: 775737590
mas "Internet Access Policy Viewer", id: 1482630322
mas "iStat Menus", id: 1319778037
mas "Jira", id: 1475897096
mas "Keep It", id: 1272768911
mas "Keynote", id: 409183694
mas "Linea Link", id: 1233368267
mas "Numbers", id: 409203825
mas "OverPicture", id: 1188020834
mas "Playgrounds", id: 1496833156
mas "Service Station", id: 1503136033
mas "Soulver", id: 413965349
mas "SwiftoDo Desktop", id: 1143641091
mas "The Unarchiver", id: 425424353
mas "Things", id: 904280696
mas "Tot", id: 1491071483
mas "Trello", id: 1278508951
mas "WiFi Explorer Lite", id: 1408727408
mas "Wipr", id: 1320666476
mas "Xcode", id: 497799835
