tap "apenngrace/vulkan"
tap "austinjones/taps"
tap "beeftornado/rmtree"
tap "caryll/tap"
tap "clementtsang/bottom"
tap "cmacrae/formulae"
tap "denisidoro/tools"
tap "dustinwilson/tap"
tap "extrawurst/tap"
tap "federico-terzi/espanso"
tap "github/gh"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "jesseduffield/lazygit"
tap "kak-lsp/kak-lsp"
tap "kkga/godot-nightly"
tap "koekeishiya/formulae"
tap "lukakerr/things"
tap "mananapr/cfiles"
tap "martido/graph"
tap "mas-cli/tap"
tap "mongodb/brew"
tap "neovim/neovim"
tap "osx-cross/arm"
tap "osx-cross/avr"
tap "qmk/qmk"
tap "ul/kak-lsp"
tap "universal-ctags/universal-ctags"
tap "vitorgalvao/tiny-scripts"
tap "wez/wezterm"
cask "osxfuse"
cask "xquartz"
brew "gdbm"
brew "sqlite"
brew "asciinema"
brew "glib"
brew "python@3.8", link: true
brew "awscli"
brew "bash"
brew "bat"
brew "icu4c"
brew "fontconfig"
brew "catimg"
brew "coreutils"
brew "dante"
brew "dark-mode"
brew "dmenu"
brew "dust"
brew "elvish"
brew "exa"
brew "exercism"
brew "fd"
brew "flac"
brew "libtool"
brew "pkg-config"
brew "libevent"
brew "libvorbis"
brew "sdl2"
brew "ffmpeg"
brew "ffsend"
brew "fish"
brew "fzf"
brew "geoip"
brew "gh"
brew "git"
brew "git-delta"
brew "git-extras"
brew "git-lfs"
brew "gnu-getopt"
brew "git-now"
brew "gnupg"
brew "gnu-sed"
brew "go"
brew "htop"
brew "hub"
brew "hyperfine"
brew "ifstat"
brew "imagemagick"
brew "irssi"
brew "jq"
brew "kakoune"
brew "lf"
brew "libuv"
brew "links"
brew "mad"
brew "make"
brew "mas"
brew "mdcat"
brew "mpc"
brew "msmtp"
brew "navi"
brew "ncdu"
brew "neofetch"
brew "neovim", args: ["HEAD"]
brew "nnn"
brew "nushell"
brew "offlineimap"
brew "oil"
brew "openvpn"
brew "osx-cpu-temp"
brew "pandoc"
brew "peco"
brew "phoronix-test-suite"
brew "procs"
brew "python@3.7"
brew "redis"
brew "rename"
brew "restic"
brew "ripgrep"
brew "ripmime"
brew "rust-analyzer"
brew "scdoc"
brew "scons"
brew "sk"
brew "speedtest-cli"
brew "starship"
brew "syncthing", restart_service: true
brew "tealdeer"
brew "telegram-cli"
brew "terminal-notifier"
brew "todo-txt"
brew "todoist"
brew "tokei"
brew "topgrade"
brew "trash"
brew "vcprompt"
brew "vulkan-headers"
brew "w3m"
brew "wget"
brew "wimlib"
brew "yadm"
brew "yasm"
brew "youtube-dl"
brew "yq"
brew "zola"
brew "zoxide"
brew "austinjones/taps/tab"
brew "clementtsang/bottom/bottom"
brew "cmacrae/formulae/spacebar"
brew "extrawurst/tap/gitui"
brew "federico-terzi/espanso/espanso"
brew "jesseduffield/lazygit/lazygit"
brew "koekeishiya/formulae/skhd"
brew "koekeishiya/formulae/yabai", args: ["HEAD"]
brew "mongodb/brew/mongodb-community@3.6", link: true
brew "qmk/qmk/qmk"
brew "ul/kak-lsp/kak-lsp"
brew "universal-ctags/universal-ctags/universal-ctags", args: ["HEAD"]
brew "vitorgalvao/tiny-scripts/cask-repair"
brew "wez/wezterm/wezterm", args: ["HEAD"]
cask "alfred"
cask "amethyst"
cask "appcleaner"
cask "balenaetcher"
cask "bitwarden"
cask "blender"
cask "brave-browser"
cask "cakebrew"
cask "coconutbattery"
cask "deckset"
cask "dejalu"
cask "dmenu-mac"
cask "docker"
cask "dozer"
cask "drawio"
cask "dropshare"
cask "etrecheckpro"
cask "figma"
cask "firefox"
cask "firefox-developer-edition"
cask "firefox-nightly"
cask "font-anka-coder"
cask "font-b612"
cask "font-cascadia"
cask "font-cozette"
cask "font-envy-code-r"
cask "font-fantasque-sans-mono"
cask "font-go-mono-nerd-font"
cask "font-hack"
cask "font-inconsolata"
cask "font-inconsolata-lgc"
cask "font-inter"
cask "font-iosevka-aile"
cask "font-jetbrains-mono"
cask "font-juliamono"
cask "font-luculent"
cask "font-m-plus"
cask "font-mononoki"
cask "font-profont-nerd-font"
cask "font-profontx"
cask "font-spleen"
cask "font-sudo"
cask "font-terminus"
cask "gifox"
cask "github"
cask "gltfquicklook"
cask "godot"
cask "godot-nightly"
cask "hammerspoon"
cask "handbrake"
cask "iina"
cask "imageoptim"
cask "intel-power-gadget"
cask "iterm2"
cask "itsycal"
cask "jitsi-meet"
cask "julia"
cask "kap"
cask "karabiner-elements"
cask "keycastr"
cask "kitty"
cask "kode54-cog"
cask "latest"
cask "little-snitch"
cask "loom"
cask "lulu"
cask "maccy"
cask "macvim"
cask "magicavoxel"
cask "menumeters"
cask "michaelvillar-timer"
cask "min"
cask "mtmr"
cask "nativedisplaybrightness"
cask "netnewswire"
cask "notable"
cask "numi"
cask "nvalt"
cask "obs"
cask "protonvpn"
cask "qmk-toolbox"
cask "quakespasm"
cask "quitter"
cask "scapple"
cask "screens-connect"
cask "sf-symbols"
cask "shifty"
cask "simplenote"
cask "sketch"
cask "slack"
cask "sloth"
cask "spotify"
cask "steam"
cask "sublime-merge"
cask "sublime-text"
cask "syncthing"
cask "table-tool"
cask "taskexplorer"
cask "taskpaper"
cask "telegram"
cask "textmate"
cask "tomighty"
cask "transmission"
cask "twine"
cask "ubersicht"
cask "unetbootin"
cask "via"
cask "vimr"
cask "viscosity"
cask "visual-studio-code"
cask "vivaldi"
cask "vorta"
cask "vulkan-sdk"
cask "zoomus"
cask "zsa-wally"
mas "1Blocker", id: 1107421413
mas "Annotate", id: 918207447
mas "app.seashore", id: 1448648921
mas "Bumpr", id: 1166066070
mas "Claquette", id: 587748131
mas "GIF Brewery 3", id: 1081413713
mas "Gifski", id: 1351639930
mas "GoodNotes", id: 1480793815
mas "iA Writer", id: 775737590
mas "iStat Menus", id: 1319778037
mas "Keep It", id: 1272768911
mas "Keynote", id: 409183694
mas "Linea Link", id: 1233368267
mas "Numbers", id: 409203825
mas "OverPicture", id: 1188020834
mas "Playgrounds", id: 1496833156
mas "Soulver", id: 413965349
mas "SwiftoDo Desktop", id: 1143641091
mas "The Unarchiver", id: 425424353
mas "Things", id: 904280696
mas "Vimari", id: 1480933944
mas "WiFi Explorer Lite", id: 1408727408
mas "Wipr", id: 1320666476
mas "Xcode", id: 497799835
