#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               on
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config window_shadow                float
yabai -m config window_border                off
yabai -m config window_border_width          1
yabai -m config active_window_border_color   0xff87875F
yabai -m config normal_window_border_color   0xff444444
yabai -m config insert_window_border_color   0xffFFFFAF
yabai -m config split_ratio                  0.60
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               ctrl
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

yabai -m config layout                       bsp
yabai -m config window_gap                   2
# yabai -m config external_bar                 all:16:0

yabai -m config --space 9 layout float

yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^App Store$"          manage=off
yabai -m rule --add app="^Activity Monitor$"   manage=off
yabai -m rule --add app="^Preview$"            manage=off
yabai -m rule --add app="^Kap$"                manage=off
yabai -m rule --add app="^Bitwarden$"          manage=off
yabai -m rule --add app="^iStat Menus Status$" manage=off
yabai -m rule --add app='^Little Snitch$'      manage=off
yabai -m rule --add app="^Quick Add to Trello$" manage=off
yabai -m rule --add app="Godot"				   manage=off
yabai -m rule --add app="^zoom.us$"            manage=off
