git:
  paging:
    colorarg: always
    # useconfig: true
    pager: delta --paging=never
# gui:
# theme:
#     lightTheme: true
# activeBorderColor:
# - yellow
# inactiveBorderColor:
# - black
# - bright
# selectedLineBgColor:
#   - reverse
# selectedRangeBgColor:
#   - reverse
startuppopupversion: 1
