git:
  paging:
    colorarg: always
    useconfig: false
    pager: delta --light --paging=never --24-bit-color=never
gui:
  theme:
    lightTheme: true
    activeBorderColor:
      - black
      - bold
    inactiveBorderColor:
      - black
startuppopupversion: 1
