git:
  paging:
    # colorarg: always
    useconfig: true
    # pager: delta --light --paging=never --24-bit-color=never
gui:
  theme:
    lightTheme: true
    activeBorderColor:
      - black
      - bold
    inactiveBorderColor:
      - yellow
startuppopupversion: 1
