git:
  paging:
    colorarg: always
    # useconfig: true
    pager: delta --paging=never
# gui:
#   theme:
#     lightTheme: true
#     activeBorderColor:
#       - black
#       - bold
#     inactiveBorderColor:
#       - white
# selectedLineBgColor:
#   - reverse
# selectedRangeBgColor:
#   - reverse
startuppopupversion: 1
