#!/usr/bin/env sh

spacebar -m config position           top
spacebar -m config height             16
spacebar -m config text_font          "Essential PragmataPro:Regular:13.0"
spacebar -m config icon_font          "Essential PragmataPro:Regular:13.0"
spacebar -m config background_color   0xff000000
spacebar -m config foreground_color   0xff999999
spacebar -m config space_icon_color   0xffffffff
spacebar -m config power_icon_color   0xff6c6c6c
spacebar -m config battery_icon_color 0xff6c6c6c
spacebar -m config dnd_icon_color     0xffa8a8a8
spacebar -m config clock_icon_color   0xffa8a8a8
spacebar -m config space_icon_strip   1 2 3 4 5 6 8 9 0
spacebar -m config power_icon_strip   - +
spacebar -m config space_icon         *
spacebar -m config clock_icon         
spacebar -m config dnd_icon           D
spacebar -m config clock_format       "%a %d-%b %R"

echo "spacebar configuration loaded.."
