" Name:         Envy
" Description:  Template for a colorscheme with dark and light variants
" Author:       Gadzhi Kharkharov <me@kkga.me>
" Maintainer:   Gadzhi Kharkharov <me@kkga.me>
" Website:      https://kkga.me/envy
" License:      Public domain
" Last Updated: Thu Sep 17 16:47:52 2020

" Generated by Colortemplate v2.0.0

hi clear
if exists('syntax_on')
  syntax reset
endif

let g:colors_name = 'envy'

let s:t_Co = exists('&t_Co') && !empty(&t_Co) && &t_Co > 1 ? &t_Co : 2
let s:italics = (&t_ZH != '' && &t_ZH != '[7m') || has('gui_running') || has('nvim')

hi! link QuickFixLine Search
hi! link StatusLineTerm StatusLine
hi! link StatusLineTermNC StatusLineNC
hi! link Boolean Constant
hi! link Character Constant
hi! link Conditional Statement
hi! link Define PreProc
hi! link Debug Special
hi! link Delimiter Special
hi! link Exception Statement
hi! link Float Constant
hi! link Function Identifier
hi! link Include PreProc
hi! link Keyword Statement
hi! link Label Statement
hi! link Macro PreProc
hi! link Number Constant
hi! link Operator Statement
hi! link PreCondit PreProc
hi! link Repeat Statement
hi! link SpecialChar Special
hi! link SpecialComment Special
hi! link StorageClass Type
hi! link String Constant
hi! link Structure Type
hi! link Tag Special
hi! link Typedef Type
hi! link lCursor Cursor

if (has('termguicolors') && &termguicolors) || has('gui_running')
  let g:terminal_ansi_colors = ['#1c1c1c', '#af5f5f', '#5f875f', '#87875f',
        \ '#5f87af', '#5f5f87', '#5f8787', '#bcbcbc', '#262626', '#ff8700',
        \ '#87af87', '#ffffaf', '#87afd7', '#8787af', '#5fafaf', '#ffffff']
  if has('nvim')
    let g:terminal_color_0 = '#1c1c1c'
    let g:terminal_color_1 = '#af5f5f'
    let g:terminal_color_2 = '#5f875f'
    let g:terminal_color_3 = '#87875f'
    let g:terminal_color_4 = '#5f87af'
    let g:terminal_color_5 = '#5f5f87'
    let g:terminal_color_6 = '#5f8787'
    let g:terminal_color_7 = '#bcbcbc'
    let g:terminal_color_8 = '#262626'
    let g:terminal_color_9 = '#ff8700'
    let g:terminal_color_10 = '#87af87'
    let g:terminal_color_11 = '#ffffaf'
    let g:terminal_color_12 = '#87afd7'
    let g:terminal_color_13 = '#8787af'
    let g:terminal_color_14 = '#5fafaf'
    let g:terminal_color_15 = '#ffffff'
  endif
  if get(g:, 'dark_transp_bg', 0) && !has('gui_running')
    hi Normal guifg=#bcbcbc guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Terminal guifg=#bcbcbc guibg=NONE guisp=NONE gui=NONE cterm=NONE
  else
    hi Normal guifg=#bcbcbc guibg=#1c1c1c guisp=NONE gui=NONE cterm=NONE
    hi Terminal guifg=#bcbcbc guibg=#1c1c1c guisp=NONE gui=NONE cterm=NONE
  endif
  hi ColorColumn guifg=NONE guibg=#262626 guisp=NONE gui=NONE cterm=NONE
  hi Conceal guifg=NONE guibg=NONE guisp=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Cursor guifg=#bcbcbc guibg=#1c1c1c guisp=NONE gui=NONE cterm=NONE
  hi CursorColumn guifg=NONE guibg=NONE guisp=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi CursorLine guifg=NONE guibg=#1c1c1c guisp=NONE gui=NONE cterm=NONE
  hi CursorLineNr guifg=#bcbcbc guibg=#1c1c1c guisp=NONE gui=NONE cterm=NONE
  hi DiffAdd guifg=#87af87 guibg=#1c1c1c guisp=NONE gui=NONE cterm=NONE
  hi DiffChange guifg=#8787af guibg=#1c1c1c guisp=NONE gui=NONE cterm=NONE
  hi DiffDelete guifg=#ff8700 guibg=#1c1c1c guisp=NONE gui=NONE cterm=NONE
  hi DiffText guifg=#bcbcbc guibg=#1c1c1c guisp=NONE gui=bold,reverse cterm=bold,reverse
  hi Directory guifg=#bcbcbc guibg=#1c1c1c guisp=NONE gui=NONE cterm=NONE
  hi EndOfBuffer guifg=#262626 guibg=#1c1c1c guisp=NONE gui=NONE cterm=NONE
  hi ErrorMsg guifg=#1c1c1c guibg=#af5f5f guisp=NONE gui=bold,reverse cterm=bold,reverse
  hi FoldColumn guifg=#6c6c6c guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Folded guifg=#6c6c6c guibg=#262626 guisp=NONE gui=NONE cterm=NONE
  hi IncSearch guifg=#bcbcbc guibg=#1c1c1c guisp=NONE gui=standout cterm=standout
  hi LineNr guifg=#6c6c6c guibg=#1c1c1c guisp=NONE gui=NONE cterm=NONE
  hi MatchParen guifg=#ffffff guibg=#6c6c6c guisp=NONE gui=NONE cterm=NONE
  hi ModeMsg guifg=#8787af guibg=#1c1c1c guisp=NONE gui=bold cterm=bold
  hi MoreMsg guifg=#bcbcbc guibg=#1c1c1c guisp=NONE gui=NONE cterm=NONE
  hi NonText guifg=#262626 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Pmenu guifg=#ffffff guibg=#6c6c6c guisp=NONE gui=NONE cterm=NONE
  hi PmenuSbar guifg=#bcbcbc guibg=#5f875f guisp=NONE gui=NONE cterm=NONE
  hi PmenuSel guifg=#262626 guibg=#bcbcbc guisp=NONE gui=NONE cterm=NONE
  hi PmenuThumb guifg=#bcbcbc guibg=#1c1c1c guisp=NONE gui=NONE cterm=NONE
  hi Question guifg=#bcbcbc guibg=#1c1c1c guisp=NONE gui=NONE cterm=NONE
  hi Search guifg=#1c1c1c guibg=#87afd7 guisp=NONE gui=NONE cterm=NONE
  hi SignColumn guifg=#6c6c6c guibg=#1c1c1c guisp=NONE gui=NONE cterm=NONE
  hi SpecialKey guifg=#262626 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi SpellBad guifg=#bcbcbc guibg=NONE guisp=#af5f5f gui=NONE cterm=NONE
  hi SpellCap guifg=#bcbcbc guibg=NONE guisp=#5f87af gui=NONE cterm=NONE
  hi SpellLocal guifg=#bcbcbc guibg=NONE guisp=#5f5f87 gui=NONE cterm=NONE
  hi SpellRare guifg=#bcbcbc guibg=NONE guisp=#5f8787 gui=reverse cterm=reverse
  hi StatusLine guifg=#1c1c1c guibg=#6c6c6c guisp=NONE gui=NONE cterm=NONE
  hi StatusLineNC guifg=#6c6c6c guibg=#262626 guisp=NONE gui=NONE cterm=NONE
  hi TabLine guifg=#bcbcbc guibg=#262626 guisp=NONE gui=NONE cterm=NONE
  hi TabLineFill guifg=#6c6c6c guibg=#1c1c1c guisp=NONE gui=NONE cterm=NONE
  hi TabLineSel guifg=#1c1c1c guibg=#ffffff guisp=NONE gui=NONE cterm=NONE
  hi Title guifg=#ffffff guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi VertSplit guifg=#262626 guibg=#262626 guisp=NONE gui=NONE cterm=NONE
  hi Visual guifg=#ffffff guibg=#6c6c6c guisp=NONE gui=NONE cterm=NONE
  hi VisualNOS guifg=#bcbcbc guibg=#1c1c1c guisp=NONE gui=NONE cterm=NONE
  hi WarningMsg guifg=#bcbcbc guibg=#1c1c1c guisp=NONE gui=NONE cterm=NONE
  hi WildMenu guifg=#bcbcbc guibg=#1c1c1c guisp=NONE gui=NONE cterm=NONE
  hi Comment guifg=#6c6c6c guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Constant guifg=#ffffaf guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Error guifg=#ff8700 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Identifier guifg=#87afd7 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Ignore guifg=#bcbcbc guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi PreProc guifg=#bcbcbc guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Special guifg=#87afd7 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Statement guifg=#ffffff guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Todo guifg=#ff8700 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Type guifg=#8787af guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Underlined guifg=#bcbcbc guibg=NONE guisp=NONE gui=underline cterm=underline
  hi CursorIM guifg=NONE guibg=fg guisp=NONE gui=NONE cterm=NONE
  hi ToolbarLine guifg=NONE guibg=#bcbcbc guisp=NONE gui=NONE cterm=NONE
  hi ToolbarButton guifg=#bcbcbc guibg=#1c1c1c guisp=NONE gui=bold cterm=bold
  hi gdscriptFunctionName guifg=#87afd7 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link gdscriptNode Special
  hi! link GitGutterAdd DiffAdd
  hi! link GitGutterChange DiffChange
  hi! link GitGutterDelete DiffDelete
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 256
  if get(g:, 'dark_transp_bg', 0)
    hi Normal ctermfg=252 ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=252 ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=252 ctermbg=237 cterm=NONE
    hi Terminal ctermfg=252 ctermbg=237 cterm=NONE
  endif
  hi ColorColumn ctermfg=NONE ctermbg=238 cterm=NONE
  hi Conceal ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=252 ctermbg=237 cterm=NONE
  hi CursorColumn ctermfg=NONE ctermbg=NONE cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=237 cterm=NONE
  hi CursorLineNr ctermfg=252 ctermbg=237 cterm=NONE
  hi DiffAdd ctermfg=108 ctermbg=237 cterm=NONE
  hi DiffChange ctermfg=177 ctermbg=237 cterm=NONE
  hi DiffDelete ctermfg=208 ctermbg=237 cterm=NONE
  hi DiffText ctermfg=252 ctermbg=237 cterm=bold,reverse
  hi Directory ctermfg=252 ctermbg=237 cterm=NONE
  hi EndOfBuffer ctermfg=238 ctermbg=237 cterm=NONE
  hi ErrorMsg ctermfg=237 ctermbg=131 cterm=bold,reverse
  hi FoldColumn ctermfg=244 ctermbg=NONE cterm=NONE
  hi Folded ctermfg=244 ctermbg=238 cterm=NONE
  hi IncSearch ctermfg=252 ctermbg=237 cterm=reverse
  hi LineNr ctermfg=244 ctermbg=237 cterm=NONE
  hi MatchParen ctermfg=231 ctermbg=244 cterm=NONE
  hi ModeMsg ctermfg=177 ctermbg=237 cterm=bold
  hi MoreMsg ctermfg=252 ctermbg=237 cterm=NONE
  hi NonText ctermfg=238 ctermbg=NONE cterm=NONE
  hi Pmenu ctermfg=231 ctermbg=244 cterm=NONE
  hi PmenuSbar ctermfg=252 ctermbg=65 cterm=NONE
  hi PmenuSel ctermfg=238 ctermbg=252 cterm=NONE
  hi PmenuThumb ctermfg=252 ctermbg=237 cterm=NONE
  hi Question ctermfg=252 ctermbg=237 cterm=NONE
  hi Search ctermfg=237 ctermbg=111 cterm=NONE
  hi SignColumn ctermfg=244 ctermbg=237 cterm=NONE
  hi SpecialKey ctermfg=238 ctermbg=NONE cterm=NONE
  hi SpellBad ctermfg=252 ctermbg=NONE cterm=NONE
  hi SpellCap ctermfg=252 ctermbg=NONE cterm=NONE
  hi SpellLocal ctermfg=252 ctermbg=NONE cterm=NONE
  hi SpellRare ctermfg=252 ctermbg=NONE cterm=reverse
  hi StatusLine ctermfg=237 ctermbg=244 cterm=NONE
  hi StatusLineNC ctermfg=244 ctermbg=238 cterm=NONE
  hi TabLine ctermfg=252 ctermbg=238 cterm=NONE
  hi TabLineFill ctermfg=244 ctermbg=237 cterm=NONE
  hi TabLineSel ctermfg=237 ctermbg=231 cterm=NONE
  hi Title ctermfg=231 ctermbg=NONE cterm=NONE
  hi VertSplit ctermfg=238 ctermbg=238 cterm=NONE
  hi Visual ctermfg=231 ctermbg=244 cterm=NONE
  hi VisualNOS ctermfg=252 ctermbg=237 cterm=NONE
  hi WarningMsg ctermfg=252 ctermbg=237 cterm=NONE
  hi WildMenu ctermfg=252 ctermbg=237 cterm=NONE
  hi Comment ctermfg=244 ctermbg=NONE cterm=NONE
  hi Constant ctermfg=229 ctermbg=NONE cterm=NONE
  hi Error ctermfg=208 ctermbg=NONE cterm=NONE
  hi Identifier ctermfg=111 ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=252 ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=252 ctermbg=NONE cterm=NONE
  hi Special ctermfg=111 ctermbg=NONE cterm=NONE
  hi Statement ctermfg=231 ctermbg=NONE cterm=NONE
  hi Todo ctermfg=208 ctermbg=NONE cterm=NONE
  hi Type ctermfg=177 ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=252 ctermbg=NONE cterm=underline
  hi CursorIM ctermfg=NONE ctermbg=fg cterm=NONE
  hi ToolbarLine ctermfg=NONE ctermbg=252 cterm=NONE
  hi ToolbarButton ctermfg=252 ctermbg=237 cterm=bold
  hi gdscriptFunctionName ctermfg=111 ctermbg=NONE cterm=NONE
  hi! link gdscriptNode Special
  hi! link GitGutterAdd DiffAdd
  hi! link GitGutterChange DiffChange
  hi! link GitGutterDelete DiffDelete
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 8
  if get(g:, 'dark_transp_bg', 0)
    hi Normal ctermfg=LightGrey ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=LightGrey ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=LightGrey ctermbg=Black cterm=NONE
    if !has('patch-8.0.0616') && !has('nvim')
      set background=light
    endif
    hi Terminal ctermfg=LightGrey ctermbg=Black cterm=NONE
  endif
  hi ColorColumn ctermfg=NONE ctermbg=DarkGrey cterm=NONE
  hi Conceal ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi CursorColumn ctermfg=NONE ctermbg=NONE cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=Black cterm=NONE
  hi CursorLineNr ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi DiffAdd ctermfg=LightGreen ctermbg=Black cterm=NONE
  hi DiffChange ctermfg=LightMagenta ctermbg=Black cterm=NONE
  hi DiffDelete ctermfg=LightRed ctermbg=Black cterm=NONE
  hi DiffText ctermfg=LightGrey ctermbg=Black cterm=bold,reverse
  hi Directory ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi EndOfBuffer ctermfg=DarkGrey ctermbg=Black cterm=NONE
  hi ErrorMsg ctermfg=Black ctermbg=DarkRed cterm=bold,reverse
  hi FoldColumn ctermfg=Grey ctermbg=NONE cterm=NONE
  hi Folded ctermfg=Grey ctermbg=DarkGrey cterm=NONE
  hi IncSearch ctermfg=LightGrey ctermbg=Black cterm=reverse
  hi LineNr ctermfg=Grey ctermbg=Black cterm=NONE
  hi MatchParen ctermfg=White ctermbg=Grey cterm=NONE
  hi ModeMsg ctermfg=LightMagenta ctermbg=Black cterm=bold
  hi MoreMsg ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi NonText ctermfg=DarkGrey ctermbg=NONE cterm=NONE
  hi Pmenu ctermfg=White ctermbg=Grey cterm=NONE
  hi PmenuSbar ctermfg=LightGrey ctermbg=DarkGreen cterm=NONE
  hi PmenuSel ctermfg=DarkGrey ctermbg=LightGrey cterm=NONE
  hi PmenuThumb ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi Question ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi Search ctermfg=Black ctermbg=LightBlue cterm=NONE
  hi SignColumn ctermfg=Grey ctermbg=Black cterm=NONE
  hi SpecialKey ctermfg=DarkGrey ctermbg=NONE cterm=NONE
  hi SpellBad ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi SpellCap ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi SpellLocal ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi SpellRare ctermfg=LightGrey ctermbg=NONE cterm=reverse
  hi StatusLine ctermfg=Black ctermbg=Grey cterm=NONE
  hi StatusLineNC ctermfg=Grey ctermbg=DarkGrey cterm=NONE
  hi TabLine ctermfg=LightGrey ctermbg=DarkGrey cterm=NONE
  hi TabLineFill ctermfg=Grey ctermbg=Black cterm=NONE
  hi TabLineSel ctermfg=Black ctermbg=White cterm=NONE
  hi Title ctermfg=White ctermbg=NONE cterm=NONE
  hi VertSplit ctermfg=DarkGrey ctermbg=DarkGrey cterm=NONE
  hi Visual ctermfg=White ctermbg=Grey cterm=NONE
  hi VisualNOS ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi WarningMsg ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi WildMenu ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi Comment ctermfg=Grey ctermbg=NONE cterm=NONE
  hi Constant ctermfg=LightYellow ctermbg=NONE cterm=NONE
  hi Error ctermfg=LightRed ctermbg=NONE cterm=NONE
  hi Identifier ctermfg=LightBlue ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi Special ctermfg=LightBlue ctermbg=NONE cterm=NONE
  hi Statement ctermfg=White ctermbg=NONE cterm=NONE
  hi Todo ctermfg=LightRed ctermbg=NONE cterm=NONE
  hi Type ctermfg=LightMagenta ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=LightGrey ctermbg=NONE cterm=underline
  hi CursorIM ctermfg=NONE ctermbg=fg cterm=NONE
  hi ToolbarLine ctermfg=NONE ctermbg=LightGrey cterm=NONE
  hi ToolbarButton ctermfg=LightGrey ctermbg=Black cterm=bold
  hi gdscriptFunctionName ctermfg=LightBlue ctermbg=NONE cterm=NONE
  hi! link gdscriptNode Special
  hi! link GitGutterAdd DiffAdd
  hi! link GitGutterChange DiffChange
  hi! link GitGutterDelete DiffDelete
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 2
  hi Normal term=NONE
  hi ColorColumn term=reverse
  hi Conceal term=NONE
  hi Cursor term=NONE
  hi CursorColumn term=reverse
  hi CursorLine term=underline
  hi CursorLineNr term=bold,italic,reverse,underline
  hi DiffAdd term=reverse,underline
  hi DiffChange term=reverse,underline
  hi DiffDelete term=reverse,underline
  hi DiffText term=bold,reverse,underline
  hi Directory term=NONE
  hi EndOfBuffer term=NONE
  hi ErrorMsg term=bold,italic,reverse
  hi FoldColumn term=reverse
  hi Folded term=italic,reverse,underline
  hi IncSearch term=bold,italic,reverse
  hi LineNr term=reverse
  hi MatchParen term=bold,underline
  hi ModeMsg term=NONE
  hi MoreMsg term=NONE
  hi NonText term=NONE
  hi Pmenu term=reverse
  hi PmenuSbar term=NONE
  hi PmenuSel term=NONE
  hi PmenuThumb term=NONE
  hi PopupSelected term=reverse
  hi Question term=standout
  hi Search term=italic,underline
  hi SignColumn term=reverse
  hi SpecialKey term=bold
  hi SpellBad term=italic,underline
  hi SpellCap term=italic,underline
  hi SpellLocal term=italic,underline
  hi SpellRare term=italic,underline
  hi StatusLine term=bold,reverse
  hi StatusLineNC term=reverse
  hi TabLine term=italic,reverse,underline
  hi TabLineFill term=reverse,underline
  hi TabLineSel term=bold
  hi Title term=bold
  hi VertSplit term=reverse
  hi Visual term=reverse
  hi VisualNOS term=NONE
  hi WarningMsg term=standout
  hi WildMenu term=bold
  hi Comment term=italic
  hi Constant term=bold,italic
  hi Error term=reverse
  hi Identifier term=italic
  hi Ignore term=NONE
  hi PreProc term=italic
  hi Special term=bold,italic
  hi Statement term=bold
  hi Todo term=bold,underline
  hi Type term=bold
  hi Underlined term=underline
  hi CursorIM term=NONE
  hi ToolbarLine term=reverse
  hi ToolbarButton term=bold,reverse
  if !s:italics
    hi CursorLineNr term=bold,reverse,underline
    hi ErrorMsg term=bold,reverse
    hi Folded term=reverse,underline
    hi IncSearch term=bold,reverse
    hi Search term=underline
    hi SpellBad term=underline
    hi SpellCap term=underline
    hi SpellLocal term=underline
    hi SpellRare term=underline
    hi TabLine term=reverse,underline
    hi Comment term=NONE
    hi Constant term=bold
    hi Identifier term=NONE
    hi PreProc term=NONE
    hi Special term=bold
  endif
  unlet s:t_Co s:italics
  finish
endif

" Background: any
" Color: black         #1c1c1c           237               Black
" Color: grey          #6c6c6c           244               Grey
" Color: red           #af5f5f           131               DarkRed
" Color: green         #5f875f           65                DarkGreen
" Color: yellow        #87875f           101               DarkYellow
" Color: blue          #5f87af           74                DarkBlue
" Color: magenta       #5f5f87           96                DarkMagenta
" Color: cyan          #5f8787           66                DarkCyan
" Color: white         #bcbcbc           252               LightGrey
" Color: brightblack   #262626           238               DarkGrey
" Color: brightred     #ff8700           208               LightRed
" Color: brightgreen   #87af87           108               LightGreen
" Color: brightyellow  #ffffaf           229               LightYellow
" Color: brightblue    #87afd7           111               LightBlue
" Color: brightmagenta #8787af           177               LightMagenta
" Color: brightcyan    #5fafaf           73                LightCyan
" Color: brightwhite   #ffffff           231               White
" Term colors: black red green yellow blue magenta cyan white
" Term colors: brightblack brightred brightgreen brightyellow
" Term colors: brightblue brightmagenta brightcyan brightwhite
" Background: any
" vim: et ts=2 sw=2
