font:
  size: 10.5
window:
  decorations: none

key_bindings:
  - { key: Return, mods: Control|Shift, action: SpawnNewInstance }

use_thin_strokes: true

cursor:
  style: Block
  vi_mode_style: Block
