font:
  # normal:
  #   family: envy code r
  #   style: regular
  # bold:
  #   family: terminus
  #   style: bold
  size: 9
  offset:
    x: 0
    y: -1
  glyph_offset:
    x: 0
    y: -1

window:
  decorations: none
  dimensions:
    columns: 100
    lines: 32

# shell:
#   program: fish

key_bindings:
  - { key: Return, mods: Control|Shift, action: SpawnNewInstance }

use_thin_strokes: true

cursor:
  style: Block
  vi_mode_style: Block
