font:
  size: 10.5

window:
  decorations: none
  dimensions:
    columns: 100
    lines: 32

# shell:
#   program: fish


key_bindings:
  - { key: Return, mods: Control|Shift, action: SpawnNewInstance }

use_thin_strokes: true

cursor:
  style: Block
  vi_mode_style: Block
