font:
  size: 12.0

draw_bold_text_with_bright_colors: true

window:
  decorations: none

# key_bindings:
#   - { key: Return, mods: Control|Shift, action: SpawnNewInstance }

cursor:
  style: Underline
  vi_mode_style: Block
